apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-helm
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
