apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: odoo
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: HOST
              value: {{ .Values.env.host }}
            - name: USER
              value: {{ .Values.env.user }}
            - name: PASSWORD
              value: {{ .Values.env.password}}
            - name: DB
              value: {{ .Values.env.db }}
