apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm
  name: {{ .Release.Name }}-helm
spec:
  ports:
  - name: http
    port: {{ .Values.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
