apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbox
  template:
    metadata:
      labels:
        app: netbox
    spec:
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: config-helm
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-helm
        - name: reports-volume
          persistentVolumeClaim:
            claimName: reports-helm
        - name: scripts-volume
          persistentVolumeClaim:
            claimName: scripts-helm
      containers:
        - name: netbox
          image: docker.io/netboxcommunity/netbox:v3.6-2.7.0
          envFrom:
            - configMapRef:
                name: netbox-env-helm
          volumeMounts:
            - name: config-volume
              mountPath: /etc/netbox/config
            - name: media-volume
              mountPath: /opt/netbox/netbox/media
            - name: reports-volume
              mountPath: /opt/netbox/netbox/reports
            - name: scripts-volume
              mountPath: /opt/netbox/netbox/scripts

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: docker.io/redis:7-alpine
        command: ["sh", "-c", "redis-server --appendonly yes --requirepass $REDIS_PASSWORD"]
        envFrom:
        - configMapRef:
            name: redis-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
      - name: redis-cache
        image: docker.io/redis:7-alpine
        command: ["sh", "-c", "redis-server --requirepass $REDIS_PASSWORD"]
        envFrom:
        - configMapRef:
            name: redis-cache-config
