apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbox
  template:
    metadata:
      labels:
        app: netbox
    spec:
      containers:
      - name: netbox
        image: docker.io/netboxcommunity/netbox:v3.6-2.7.0
        envFrom:
        - configMapRef:
            name: netbox-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/postgres:15-alpine
        envFrom:
        - configMapRef:
            name: postgres-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: docker.io/redis:7-alpine
        command: ["sh", "-c", "redis-server --appendonly yes --requirepass $REDIS_PASSWORD"]
        envFrom:
        - configMapRef:
            name: redis-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
      - name: redis-cache
        image: docker.io/redis:7-alpine
        command: ["sh", "-c", "redis-server --requirepass $REDIS_PASSWORD"]
        envFrom:
        - configMapRef:
            name: redis-cache-config
