apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: netbox
            - name: POSTGRES_USER
              value: netbox
            - name: POSTGRES_PASSWORD
              value: J5brHrAXFLQSif0K
